- name: get gfx infos
  shell: "lspci | grep VGA"
  register: gfxinfo

- name: looking for nvidia drivers
  shell: "apt list --installed"
  register: nv_installed
  ignore_errors: true

- name: set install flag
  set_fact:
    install: true
  when: gfxinfo.stdout is search('Virtio') or (gfxinfo.stdout is search('NVIDIA') and nv_installed.stdout is not search('nvidia-driver'))

- name: looking for activated secure boot
  shell: "mokutil --sb-state"
  register: sb_state
  ignore_errors: true

- name: set secure_boot flag
  set_fact:
    secure_boot: "{{ 'true' if 'SecureBoot enabled' in sb_state.stdout else 'false' }}"

- name: update apt
  apt:
    update_cache: yes
  when: install

- name: prepare expect script
  copy:
    src: install-nvidia-drivers.exp
    dest: /run/install-nvidia-drivers.exp
  when: install and secure_boot

- name: install nvidia dkms drivers with enabled secure boot
  command: expect -d /run/install-nvidia-drivers.exp
  when: install and secure_boot

- name: install nvidia dkms drivers with disabled secure boot
  apt:
    pkg:
      - nvidia-driver-570
    install_recommends: yes
    update_cache: no
  when: install and not secure_boot

- name: waiting for dpkg to finish
  shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done;
  when: install

- name: remove nouveau driver
  apt:
    pkg:
      - xserver-xorg-video-nouveau
    state: absent
  when: install

- name: remove unused packages
  apt:
    autoclean: yes
  when: install

- name: reinstall required packages
  apt:
    pkg:
      - libxatracker2
      - libxvmc1
      - xserver-xorg-video-amdgpu
      - xserver-xorg-video-ati
      - xserver-xorg-video-fbdev
      - xserver-xorg-video-intel
      - xserver-xorg-video-qxl
      - xserver-xorg-video-radeon
      - xserver-xorg-video-vesa
    install_recommends: true
  when: install
    